version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        image: php:8.0-apache
        volumes:
          - ./www:/var/www/html/
        ports:
          - 8001:80
        depends_on:
            - db
        networks:
            - default
    db:
        image: mysql
        container_name: db
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
            #- ./mysql/my.cnf:/etc/my.cnf
            #- ./mysql/my.cnf.d:/etc/my.cnf.d
            #- ./mysql/mysql:/etc/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
volumes:
    persistent:
